language: cpp
compiler: g++
git:
  quiet: true
  depth: 1

notifications:
  email: false

cache:
  - apt

sudo: required

matrix:
  include:

    # Linux
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-7-dev
            - cmake
            - doxygen
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - CXX_COMPILER="clang++"
        - C_COMPILER="clang"

before_install:
  - eval "${MATRIX_EVAL}"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install llvm-dev doxygen git g++ gcc libgmp-dev libmpfr-dev make libppl-dev && git clone https://github.com/antoinemine/apron && cd apron && ./configure -no-java -no-ocaml -no-ppl && make && sudo make install && cd ..; fi
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=`which clang` -DCMAKE_CXX_COMPILER=`which clang++` ..
  - make -j2
  - make check

