language: cpp
compiler: clang
git:
  quiet: true
  depth: 1

notifications:
  email: false

sudo: required

matrix:
  include:

    # Linux
    os: linux
    dist: bionic
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - llvm-dev
          - cmake
          - doxygen
    env:
      - MATRIX_EVAL="CC=clang && CXX=clang++"
      - CXX_COMPILER="clang++"
      - C_COMPILER="clang"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER ..
  - make -j2
  - make check

